apiVersion: v1
kind: Secret
metadata:
  name: netbox-secret
  namespace: netbox
type: Opaque
stringData:
  # NetBox 必須
  SECRET_KEY: "CHANGE_ME_TO_LONG_RANDOM_STRING"

  # NetBox が参照するDB/Redisパスワード
  DB_PASSWORD: "netboxpass"
  REDIS_PASSWORD: "redispw"

  # 初期管理者（不要なら後で作成でもOK）
  SUPERUSER_NAME: "admin"
  SUPERUSER_EMAIL: "admin@example.com"
  SUPERUSER_PASSWORD: "ChangeMe123!"
