apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: netbox
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-secret
                  key: REDIS_PASSWORD
          command: ["sh","-lc"]
          args:
            - |
              exec redis-server \
                --appendonly no \
                --requirepass "${REDIS_PASSWORD}"
          volumeMounts:
            - name: redisdata
              mountPath: /data
      volumes:
        # 一旦用（永続化しない）
        - name: redisdata
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: netbox
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
