apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  namespace: netbox
  labels:
    app: netbox
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: netbox
  template:
    metadata:
      labels:
        app: netbox
    spec:
      initContainers:
        - name: wait-backends
          image: busybox:1.36
          envFrom:
            - configMapRef:
                name: netbox-config
            - secretRef:
                name: netbox-secret
          command: ["sh","-lc"]
          args:
            - |
              echo "[wait] postgres ${DB_HOST}:${DB_PORT}"
              until nc -z -w2 "${DB_HOST}" "${DB_PORT}"; do sleep 2; done
              echo "[wait] redis ${REDIS_HOST}:${REDIS_PORT}"
              until nc -z -w2 "${REDIS_HOST}" "${REDIS_PORT}"; do sleep 2; done
              echo "[wait] OK"

      containers:
        - name: netbox
          image: netboxcommunity/netbox:v4.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080

          envFrom:
            - configMapRef:
                name: netbox-config
            - secretRef:
                name: netbox-secret

          # 起動完了判定（認証不要で200/302が返る場所に統一）
          startupProbe:
            httpGet:
              path: /login/
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 120   # 10分まで起動待ち

          readinessProbe:
            httpGet:
              path: /login/
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /login/
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: netbox
spec:
  selector:
    app: netbox
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.1.70
