apiVersion: v1
kind: Service
metadata:
  name: es-devops-lb
  namespace: devops
spec:
  type: LoadBalancer
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: es-devops
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
