apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.13.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/
        - name: log-volume
          mountPath: /usr/share/logstash/logs/
      volumes:
      - name: config-volume
        configMap:
          name: logstash-pipeline
      - name: log-volume
        emptyDir: {}
