apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
  namespace: log
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.1.65
  selector:
    app: logstash
  ports:
  - port: 80
    targetPort: 8080
