apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-arista-configbackup
  namespace: tools  # 使用するネームスペース
  labels:
    app: daily-arista-configbackup
spec:
  #schedule: "CRON_TZ=Asia/Tokyo 00 08 * * 6,0"
  schedule: "00 08 * * *"
  timeZone: "Asia/Tokyo"
  successfulJobsHistoryLimit: 0  # 成功したジョブを1つのみ保持、それ以外は削除
  failedJobsHistoryLimit: 1  # 失敗したジョブを1つのみ保持、それ以外は削除
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: github-secret  # 使用するSecretの名前
          containers:
          - name: daily-arista-configbackup
            image: github-container-image  # コンテナイメージ
            command:
            - /usr/bin/perl
            - /app/arista-backup/main-backup.pl  # 実行するコマンド
            volumeMounts:
            - name: nfs-storage
              mountPath: /nfs  # pv
          restartPolicy: Never  # 実行失敗時に再試行
          volumes:
          - name: nfs-storage
            persistentVolumeClaim:
              claimName: nfs-pvc  # 使用するPVCの名前
