apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
  namespace: dns
data:
  unbound.conf: |
    server:
      verbosity: 2

      interface: 0.0.0.0
      port: 53
      do-ip4: yes
      do-udp: yes
      do-tcp: yes

      # source
      access-control: 0.0.0.0/0 allow

      # 標準出力にログを出すkubectl logs
      logfile: ""
      use-syslog: no
      log-time-ascii: yes

      # クエリログを有効化（IP + ドメイン）
      log-queries: yes
      # 返信も出したければ yes に（任意）
      log-replies: no
      # SERVFAIL だけ別途見たいとき
      log-servfail: yes

      # キャッシュ関連（お好みで調整）
      cache-max-ttl: 86400
      cache-min-ttl: 3600
      num-threads: 2
      msg-cache-size: 128m
      rrset-cache-size: 256m
      infra-cache-numhosts: 10000

    forward-zone:
      name: "."
      forward-first: yes
      forward-addr: 8.8.8.8
      forward-addr: 8.8.4.4
      forward-addr: 1.1.1.1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: dns
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: mvance/unbound:latest
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: unbound-config
              mountPath: /opt/unbound/etc/unbound/unbound.conf
              subPath: unbound.conf
      volumes:
        - name: unbound-config
          configMap:
            name: unbound-config
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: dns
spec:
  type: LoadBalancer
  selector:
    app: unbound
  loadBalancerIP: 192.168.1.65
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
